/**
 * Golden fixture regression tests — TS engine vs Python oracle.
 *
 * Loads __fixtures__/scenarios.json generated by `scripts/gen-fixtures.py`
 * from the validated v0 Python cost_model.py, then asserts each of the
 * 27 paired checks matches within ±0.001.
 *
 * If any assertion fails, Phase 1 gate fails and no subsequent phase may start.
 */

import { describe, it, expect } from "vitest";
import {
  calculate,
  applyLoadingChange,
  applyLaborChange,
  applyMaterialYieldChange,
  applyCutsMaskChange,
  applyTactInvestmentChange
} from "./engine";
import {
  REFERENCE_CASE1,
  REFERENCE_CASE2,
  REFERENCE_CASE4,
  REFERENCE_CASE5,
  REFERENCE_CASE6
} from "./presets";
import scenarios from "./__fixtures__/scenarios.json";
import references from "./__fixtures__/references.json";

const TOLERANCE = 0.001;

function closeTo(actual: number, expected: number, label: string): void {
  const diff = Math.abs(actual - expected);
  if (diff > TOLERANCE) {
    throw new Error(
      `${label}: expected ${expected}, got ${actual} (diff=${diff.toExponential(3)})`
    );
  }
}

describe("Phase 1 — Cost Engine Golden Fixture Regression", () => {
  // ─── References: sanity check (6 presets match Python calculate output) ───
  it("reference case 1 matches Python fixture", () => {
    const r = calculate(REFERENCE_CASE1);
    const f = (references as any).case1.result;
    expect(Math.abs(r.cop - f.cop)).toBeLessThan(TOLERANCE);
    expect(Math.abs(r.material_cost - f.material_cost)).toBeLessThan(TOLERANCE);
    expect(Math.abs(r.processing_cost - f.processing_cost)).toBeLessThan(TOLERANCE);
  });

  it("reference case 2 matches Python fixture", () => {
    const r = calculate(REFERENCE_CASE2);
    const f = (references as any).case2.result;
    expect(Math.abs(r.cop - f.cop)).toBeLessThan(TOLERANCE);
    expect(Math.abs(r.sga - f.sga)).toBeLessThan(TOLERANCE);
  });

  // ─── Case 1: Loading 70%→50% (6 assertions) ───
  describe("Case 1 — Loading 70%→50%", () => {
    const sim = applyLoadingChange(REFERENCE_CASE1, 0.5);
    const r = calculate(sim);
    const f = (scenarios as any).case1_loading_50.result;

    it("1. Panel 노무비", () => closeTo(r.panel_labor, f.panel_labor, "panel_labor"));
    it("2. Panel 경비", () => closeTo(r.panel_expense, f.panel_expense, "panel_expense"));
    it("3. Panel 상각비", () =>
      closeTo(r.panel_depreciation, f.panel_depreciation, "panel_depreciation"));
    it("4. Module 노무비", () => closeTo(r.module_labor, f.module_labor, "module_labor"));
    it("5. Module 경비", () => closeTo(r.module_expense, f.module_expense, "module_expense"));
    it("6. Module 상각비", () =>
      closeTo(r.module_depreciation, f.module_depreciation, "module_depreciation"));
  });

  // ─── Case 2: 인건비 1.5배 (5 assertions) ───
  describe("Case 2 — 인건비 1.5배", () => {
    const sim = applyLaborChange(REFERENCE_CASE2, 1.5);
    const r = calculate(sim);
    const f = (scenarios as any).case2_labor_1_5x.result;

    it("7. Panel 노무비", () => closeTo(r.panel_labor, f.panel_labor, "panel_labor"));
    it("8. Module 노무비", () => closeTo(r.module_labor, f.module_labor, "module_labor"));
    it("9. SGA 합계", () => closeTo(r.sga, f.sga, "sga"));
    it("10. COP", () => closeTo(r.cop, f.cop, "cop"));
    it("11. 영업이익", () =>
      closeTo(r.operating_profit, f.operating_profit, "operating_profit"));
  });

  // ─── Case 4: 재료비-5% + 수율-4%p (3 assertions) ───
  describe("Case 4 — 재료비 -5% + 수율 -4%p", () => {
    const sim = applyMaterialYieldChange(REFERENCE_CASE4, -0.05, -0.04);
    const r = calculate(sim);
    const f = (scenarios as any).case4_mat_m5_yield_m4p;

    it("12. Module BOM", () =>
      closeTo(sim.bom.module, f.params_after.bom.module, "bom.module"));
    it("13. Module 수율", () =>
      closeTo(sim.yields.module, f.params_after.yields.module, "yields.module"));
    it("14. 소요재료비", () =>
      closeTo(r.material_cost, f.result.material_cost, "material_cost"));
  });

  // ─── Case 5a: 면취수 25→29 (6 assertions) ───
  describe("Case 5a — 면취수 25→29", () => {
    const sim = applyCutsMaskChange(REFERENCE_CASE5, 25, 29, 6, 6);
    const r = calculate(sim);
    const f = (scenarios as any).case5a_cuts_25_29;

    it("15. TFT BOM", () => closeTo(sim.bom.tft, f.params_after.bom.tft, "bom.tft"));
    it("16. CF BOM", () => closeTo(sim.bom.cf, f.params_after.bom.cf, "bom.cf"));
    it("17. Cell BOM", () => closeTo(sim.bom.cell, f.params_after.bom.cell, "bom.cell"));
    it("18. Panel 노무비", () =>
      closeTo(r.panel_labor, f.result.panel_labor, "panel_labor"));
    it("19. Panel 경비", () =>
      closeTo(r.panel_expense, f.result.panel_expense, "panel_expense"));
    it("20. Panel 상각비", () =>
      closeTo(r.panel_depreciation, f.result.panel_depreciation, "panel_depreciation"));
  });

  // ─── Case 5b: 면취수 25→29 + Mask 6→7 (3 assertions) ───
  describe("Case 5b — 면취수 25→29 + Mask 6→7", () => {
    const sim = applyCutsMaskChange(REFERENCE_CASE5, 25, 29, 6, 7);
    const r = calculate(sim);
    const f = (scenarios as any).case5b_cuts_mask.result;

    it("21. Panel 노무비", () => closeTo(r.panel_labor, f.panel_labor, "panel_labor"));
    it("22. Panel 경비", () => closeTo(r.panel_expense, f.panel_expense, "panel_expense"));
    it("23. Panel 상각비", () =>
      closeTo(r.panel_depreciation, f.panel_depreciation, "panel_depreciation"));
  });

  // ─── Case 6a: Tact 1.2X (3 assertions) ───
  describe("Case 6a — Tact 1.2X", () => {
    const sim = applyTactInvestmentChange(REFERENCE_CASE6, 1.2, 0.0);
    const r = calculate(sim);
    const f = (scenarios as any).case6a_tact_1_2x.result;

    it("24. Module 노무비", () => closeTo(r.module_labor, f.module_labor, "module_labor"));
    it("25. Module 경비", () => closeTo(r.module_expense, f.module_expense, "module_expense"));
    it("26. Module 상각비", () =>
      closeTo(r.module_depreciation, f.module_depreciation, "module_depreciation"));
  });

  // ─── Case 6b: Tact 1.2X + 투자 +1.9 (1 assertion) ───
  describe("Case 6b — Tact 1.2X + 투자 13억", () => {
    const sim = applyTactInvestmentChange(REFERENCE_CASE6, 1.2, 1.9);
    const r = calculate(sim);
    const f = (scenarios as any).case6b_tact_invest.result;

    it("27. Module 상각비 (투자 포함)", () =>
      closeTo(r.module_depreciation, f.module_depreciation, "module_depreciation"));
  });
});
